### ISSUE TITLE
Currency Symbol to Table Header

### ISSUE THREAD

**Issue by foreachthing** [no-preserve-root/invoice2#5]
I'd like the currency symbol to be in the header only.
If you use `currency-symbol={CHF}`, a lot space is wasted.
![image](https://user-images.githubusercontent.com/10420187/32432914-8668c0ac-c2d9-11e7-8e04-79627ad290d3.png)

Also, these settings are used in Switzerland:
`\NewTranslation{swissgerman}{invoice2-thousands-sep}{'}`
`\NewTranslation{swissgerman}{invoice2-decimal-point}{.}`

**Comment by no-preserve-root** [comment]
Actually done, wrong issue # in commit msg
